# Generated by Django 5.1.4 on 2024-12-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths_bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='api_key',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
